# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'workwith' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for workwith


  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  target 'workwithTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


